### ISSUE TITLE
Can't edit cavatica link

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#1048]
**Sender**: bailey@d3b.center
**Comment**: Trying to Copy/paste the link to Teachey's delivery project. Figured i could get the full link if I click "edit" next to the cavatica project link. When clicking edit - i just get this blank page. If i use the back. button in the browser - all pages remain blank.
[Open #126 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/126)

<a href='https://usersnappublic.s3.amazonaws.com/2021-05-26/21-37/b23b7904-2a1c-4151-8f58-e1700722763a.png'>![⚠️ - Can't edit cavatica link](https://usersnappublic.s3.amazonaws.com/2021-05-26/21-37/02bf3684-7505-4c71-ab77-15a4e50060ce.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-05-26/21-37/b23b7904-2a1c-4151-8f58-e1700722763a.png'>Download original image</a>

**Browser**: Chrome 90 (Macintosh)
**Referer**: [https://data-tracker.kidsfirstdrc.org/study/SD_AQ9KVN5P/cavatica](https://data-tracker.kidsfirstdrc.org/study/SD_AQ9KVN5P/cavatica)
**Screen size**: 1920 x 1080 **Browser size**: 1585 x 887

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by XuTheBunny** [comment]
Obsolete
