### ISSUE TITLE
Investigator Submission for Review

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#111]
As an Investigator, I would like to visit the data tracker to view the state of my submitted files and submit new files for review. Specifically, I would like to create a new `packet` of files, request DRC approval, and receive feedback on why files are not up to spec from the DRC so that I may correct them.

- Create submission `packets` or `bundles` for an investigator to create with files and a summary description
- Allow DRC admins to add comments to a `packet` and return it to the investigator
- Allow DRC admins to approve a `packet`

**Comment by bdolly** [comment]
@dankolbman can you elaborate on the `packet` idea as initially, we moved away from this concept in favor of single file processing using the status tags

**Comment by dankolbman** [comment]
I suppose a `packet` is just an arbitrary amount of files to be approved together. I wasn't aware that we moved away from that concept, but if we go with single file process, it's more or less the same except a `packet` now just has one file.

The outline above is more or less describing the need for an approval process of some type.
