### ISSUE TITLE
Mask/hide dev tokens on tokens page

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-data-tracker#150]
I think allison brought this up before, but I don't see an issue for it yet

**Comment by dankolbman** [comment]
Will return the full token only in the mutation to get a new one and display it along with a message warning the user that it will not be fully visible again.
We will make modifications to the `allTokens` query to only return the first 4 characters of a token to prevent retrieving full tokens from the API.

**Comment by dankolbman** [comment]
Tokens will now be masked from the api side
