### ISSUE TITLE
Study text filter

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-ui-data-tracker#152]
So for #151 I ended up just doing ctrl-f a lot to find the studies of interest. Could we have a filter box to type in that searches against the study entity, especially as we continue to get more studies in the future and might consider paginating?

**Comment by bdolly** [comment]
@allisonheath the original design that is not yet implemented has studies grouped by investigator
@dankolbman is there a ticket to address this?

**Comment by dankolbman** [comment]
@bdolly see #159 #112

**Comment by bdolly** [comment]
@dankolbman I just fear that if we throw a soft search filter in there the actual design will never get implemented and provide a better experience internally at the cost of a worse experiment externally

**Comment by dankolbman** [comment]
I'm not sure the original design holds up any better for our internal use. We may consider two different views to address each, and simply not allow end users to see the internal view.

**Comment by bdolly** [comment]
I think the issue now is that the study short name and investigator aren't shown on the cards. Maybe in the short-term we simply add a list / grid view toggle. 

@allisonheath thoughts?
