### ISSUE TITLE
Rename next step after upload

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-ui-data-tracker#154]
![image](https://user-images.githubusercontent.com/2213854/55813230-72ec0c80-5aba-11e9-8be3-daede2d377aa.png)

Seems like this is being reused for two different functions. The first is when you're actually uploading the file, and "annotate file" doesn't make sense because the file isn't actually in the system yet, you're uploading with a description, also some sort of arrow or better indication that moves the workflow forward.

I see now that when you have uploaded and you click the pencil:
![image](https://user-images.githubusercontent.com/2213854/55813616-10474080-5abb-11e9-9093-89c77acead60.png)
You get the same screen, and now it makes more sense that you're "annotating". Although I might suggest making it more explicit like "Update Description".

**Comment by bdolly** [comment]
@allisonheath the idea originally is that you **must** annotate a file before it can be uploaded into the system. This is our minimal constraint requiring investigators to explain their files to help out the data mungers. 

Filed in #122

**Comment by allisonheath** [comment]
Yeah, I understand the requirement. What I'm saying is how the requirement translates to the user's view of what's happening could use some adjustments so it's not confusing.

With the current flow, the first action is actually two functions in one: annotate *and* upload (I think I like the term "describe" better since the box is called `File Description` not `File Annotation`, but the primary reason you're there is to the upload the file. So for example, you could just have it say `Upload` and notify a description is required if they haven't provided one. Then second action is just `Update Description', as far as I can tell, you can't re-upload the file?
