### ISSUE TITLE
Badges look like buttons

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-ui-data-tracker#155]
![image](https://user-images.githubusercontent.com/2213854/55813894-8ea3e280-5abb-11e9-83ed-cb2f66c162ab.png)

**Comment by dankolbman** [comment]
Should consider this before proceeding with kids-first/kf-uikit#107
@XuTheBunny @bdolly

**Comment by bdolly** [comment]
to my knowledge these aren't functional yet, as in they are just hard coded and there's nothing implemented to change their status. @dankolbman is that correct?
