### ISSUE TITLE
File list declutter

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-ui-data-tracker#157]
![image](https://user-images.githubusercontent.com/2213854/55814381-64065980-5abc-11e9-8490-942c38e94a69.png)

Even after just three files, there's a lot to pick out to say, edit the annotation for the middle file. 

Dropbox solves this by hiding the actions until you hover:
![Screen Shot 2019-04-09 at 11 42 24 AM](https://user-images.githubusercontent.com/2213854/55814483-a7f95e80-5abc-11e9-9d41-0907d21942d2.png)

Google solves this by having the actions at the top right after you've selected the files
![Screen Shot 2019-04-09 at 11 43 34 AM](https://user-images.githubusercontent.com/2213854/55814518-bcd5f200-5abc-11e9-9736-406fb9ed3824.png)

Also the names, ids, etc, should be all lined up and not adjusted based on the file name length.

**Comment by dankolbman** [comment]
Possible related to #103 #104 #123 and #124

**Comment by allisonheath** [comment]
Yeah, looks like this is well covered by previous issues, so we should make sure those happen in the next sprint.
