### ISSUE TITLE
File version timeline

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#176]
Users should be able to browse a file's version history under the file's page. This history should display a list of versions for the file, the time the version was created, and allow the user to download them.

**Comment by bdolly** [comment]
no current design exists for this, will need to create one and link in ticket

**Comment by bdolly** [comment]
File Version Detail View mockup https://invis.io/2RQP4OEUAS3#/362055881_5-1_Study_Detail__Files_SingleFile

**Comment by bdolly** [comment]
@dankolbman is #219 a duplicate of this?

**Comment by dankolbman** [comment]
@bdolly no, @219 is for the design, this is the implementation.
