### ISSUE TITLE
getting the download url for a file is almost impossible

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#191]
Right now I have to either carefully select just the KFID and copy or click the copy button and then dismiss a modal dialog and then manually cobble together just the right endpoint navigation to build the URL. Ideally I'd be able to get the full download URL without so much effort.

As far as I can tell, the only reason the copy button currently exists is because double-clicking on the file KFID doesn't do the right thing (It selects more than just the kfid). Can we at least remove that button and make it so that double-clicking the kfid selects just the kfid?

**Comment by dankolbman** [comment]
Can we fix the double-click to select the kf_id and still keep the button as an alternate method of copying?

**Comment by fiendish** [comment]
Sure. Can the alert be made transient and not a modal that needs to be dismissed?

**Comment by fiendish** [comment]
As a person who needs to create an ingest configuration pointing at a particular version of a particular file, I need to be able to _see_  the whole download URL for every version of every file. 

At the very least I need to see see the version kfid for every version of every file and not just document kfids.

**Comment by dankolbman** [comment]
I believe the issue being raised now is a bit different from what was originally posted. We can continue this in another issue.
I think the originally problem was the inability to simply get the download url for a file, but this has been provided in the copy download link button. We can open a new issue to also support getting the download link from the download button itself.
