### ISSUE TITLE
make File Name Annotation field a standard text input 

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-data-tracker#199]
While the design called for the edit icon, seeing it in development I think it should be a standard text input element to make it more clear that this is a form. 

:thinking:  should we make the file extension editable as well ?
@dankolbman thoughts?

**Live**
![Screen Shot 2019-04-23 at 5.12.09 PM.png](https://images.zenhubusercontent.com/5a8b15ba4b5806bc2bc7866e/aca26694-48aa-4e49-b0e4-4072fecfaa2b)

**Comment by dankolbman** [comment]
Maybe we should just strip off the file extension as part of the name on the upload, that way the extension is non-editable.
