### ISSUE TITLE
Contacts on study header is same for all studies

### ISSUE THREAD

**Issue by parimalak** [kids-first/kf-ui-data-tracker#207]
<img width="1028" alt="Screen Shot 2019-04-25 at 11 39 49 AM" src="https://user-images.githubusercontent.com/20447220/56749040-f3fc0280-674e-11e9-8a22-85bead139311.png">

**Comment by dankolbman** [comment]
Duplicate of #158. We can't populate this field properly until we decide where the investigator information should be stored.
