### ISSUE TITLE
new token creation still displays just-created token

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#208]
Maybe it shouldn't, because it exposes the token to shoulder surfing

**Comment by dankolbman** [comment]
Do you mean that the token name stays populated in the new token form input, or that the token contents are visible in the list?
As far as the token visible in the list, this is usually how I've seen tokens like this implemented. What method would you rather see?

**Comment by fiendish** [comment]
I saw that you added a copy button, so maybe don't show the token and just make the person click that button if they want to copy the newly created token.

**Comment by dankolbman** [comment]
I'm not convinced this is a major issue. The tokens being visible after being created is necessary for the user to be able to copy the token. The tokens are not returned to the client the next time the page is loaded, ensuring that they are only available up front. This arguably makes them vulnerable to shoulder peeking, but I believe there are far bigger concerns than that such as how the creator really has no restrictions on how they are stored anyway.

Will mark this as wontfix for the time being as it seems to be functionally adequate.
