### ISSUE TITLE
file edit cancel button is secretly just a browser back button

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#238]
1) Authenticate to https://kf-ui-data-tracker.kidsfirstdrc.org/
2) open a new tab
3) go to https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_46SK55A3/files/SF_KRSKVJJB
4) click cancel  (nothing happens)

<hr>

1) Authenticate to https://kf-ui-data-tracker.kidsfirstdrc.org/
2) go to https://apple.com
3) go to https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_46SK55A3/files/SF_KRSKVJJB
4) click cancel (you're taken to apple.com)

<hr>

The cancel button shouldn't just be a back button. The browser already has a back button.

**Comment by dankolbman** [comment]
Should be fixed now.
