### ISSUE TITLE
site refuses to display without javascript for no reason

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#242]
nothing that this site does should require javascript

**Comment by dankolbman** [comment]
:)

**Comment by fiendish** [comment]
The only components that need javascript are drag-and-drop for file uploading and those tiny clipboard icons. Those could be disabled selectively and keep the rest of the site working.

**Comment by bdolly** [comment]
It's a single page web application, it's rendering and functionality is entirely driven by javascript
