### ISSUE TITLE
Delete file returns 400 due to "cannot query kfId field" 

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-ui-data-tracker#246]
Might be a study creator API issue, but since it happened while using the app, I'm filing it here first. 

When I try to delete a study file via the delete icon, the file does not get removed from the list. The delete request fails and returns a 400 status with this message:
```
{"errors":[{"message":"Cannot query field \"kfId\" on type \"DeleteFileMutation\".","locations":[{"line":3,"column":5}]}]}
```
Seems like the schema changed on the API and isn't accounted for on the app side

**Comment by dankolbman** [comment]
It looks like the api did not get promoted last release, which included this change. Will have to run it again.
