### ISSUE TITLE
Update mockups to adjust File Version flow to account for version messages 

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-data-tracker#259]
Update existing file version mockups https://invis.io/2RQP4OEUAS3#/362055881_5-1_Study_Detail__Files_SingleFile to allow users to add and view messages attached to each file version. 

User Flow: 
1. click `Upload Version`
2. Upload a file 
3. present user with helpful action copy and a textarea for the version message 
4. allow user to `Confirm/Upload` new file version

**Comment by dankolbman** [comment]
Mockups were updated with new flow. Will follow with issues to make changes an needed.
