### ISSUE TITLE
💄create better error page design and handling 

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-data-tracker#310]
<img width="2554" alt="Screen Shot 2019-06-13 at 10 43 45 AM" src="https://user-images.githubusercontent.com/1334131/59442545-6e004d80-8dc8-11e9-8cc2-e67c05181539.png">
 Right now we just cough up the raw graphql error which is only helpful for developers. A more stylized and thoughtful design needs to be made for an error page prompting users to contact support if the error continues

**Comment by XuTheBunny** [comment]
Use Semantic Message component as a standard way handling all error messages.
