### ISSUE TITLE
Put download links behind a proxy path so that they can be real hyperlinks

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#393]
This is related to https://github.com/kids-first/kf-ui-data-tracker/issues/191#issuecomment-518790388

The file download links use a dynamic javascript/graphql dance to generate a new single-use-only token for downloading every time you click the download button.

This negatively impacts the download links themselves because you can't right-click on them to do things like Copy URL or Save As.

Would it be possible to move that token and request dance one layer away through an `a` tag with href `"/download/study/{study}/file/{docid}/version/{verid}"` that's always available when the page is rendered?

**Comment by dankolbman** [comment]
We may be able to make a 'sharable' url that presents a download of a specific version in the following way:
- Make versions have a static route in the app eg: `/studies/SD_XXX/documents/SF_XXX/version/FV_XXX`
- Have an additional route for `/download` relative to the previous route that will spawn the file download

This way, we can allow users to share that given route which, when clicked, will first auth the user through the regular flow, then point them to the version modal and immediately prompt the download.

The downside here is that the given route will still not be accessible through `curl` or standard GET requests to that endpoint.

**Comment by fiendish** [comment]
> *The downside here is that the given route will still not be accessible through curl or standard GET requests to that endpoint.*

I don't follow why that needs to be true if the request can include authorization headers.

**Comment by dankolbman** [comment]
Headers are not supported for standard GET requests within the browser.

**Comment by fiendish** [comment]
You already proposed a mechanism for how to handle the browser.

**Comment by dankolbman** [comment]
The `/studies/SD_XXX/documents/SF_XXX/version/FV_XXX` route provides a given version of a document in a study but may only be accessed with the correct `Authorization` header or download code. I'm not sure how we can utilize a proxy to turn these into real hyperlinks. I'm unsure of how to support some of the basic browser behavior while still solving our primary use cases.

**Comment by fiendish** [comment]
When you click the current download link, where is the information that that uses to authenticate you stored?
