### ISSUE TITLE
Change colors of File Status indicators to be more a11y friendly 

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-data-tracker#397]
# [Document Status Visibility](https://airtable.com/tbluh9vFA7rg1K2h1/viwAmPuoQyVYzXyZb/rec9ETu6Bru4ghXhd?blocks=hide)

## Enhancement

Update the colors for "Pending Review" and "Changes Needed" to have more contrast as many participants had difficulty distinguishing them apart. 

## Evidence 
<img width="239" alt="Screen Shot 2019-08-12 at 1 43 01 PM" src="https://user-images.githubusercontent.com/1334131/62886030-47975980-bd08-11e9-9c67-96a0a845eedb.png">

<img width="149" alt="Screen Shot 2019-08-12 at 1 43 34 PM" src="https://user-images.githubusercontent.com/1334131/62886042-5120c180-bd08-11e9-8716-448289a2e1b6.png">

> "... changes needed up at the top, now I can see I'm just color blind. ... it's just hard because it's merged in with pending review .. "

<img width="315" alt="Screen Shot 2019-08-12 at 1 44 41 PM" src="https://user-images.githubusercontent.com/1334131/62886050-541bb200-bd08-11e9-8306-eb78494900d0.png">

<img width="176" alt="Screen Shot 2019-08-12 at 1 56 10 PM" src="https://user-images.githubusercontent.com/1334131/62886299-fa67b780-bd08-11e9-9d62-f4de57608496.png">

**Comment by XuTheBunny** [comment]
As reference, this is the color options from Semantic.
![image](https://user-images.githubusercontent.com/32206137/62891505-e2496580-bd13-11e9-887b-18142c465c08.png)

**Comment by dankolbman** [comment]
Removed file statuses so no longer relevant.
