### ISSUE TITLE
add user friendly time formats to TimeAgo on hover

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-data-tracker#401]
## Topic 

File List Navigation

## Enhancement 

On hover of the `TimeAgo` component replace the text with a user friendly formatted exact timestamp in the format of `dd/mm/yy hh:mm am/pm`. This pattern should be used for all instances of the TimeAgo component

## Evidence 

When ask to identify the most recently updated version of these two documents particiapnts were frustrated and unable to complete the task. Only a few participants hovered over the `Created ... ` text long enough to see the title tooltip and were still unable to identify the correct document due to formatting issues. 

<img width="772" alt="Screen Shot 2019-08-12 at 2 42 19 PM" src="https://user-images.githubusercontent.com/1334131/62889564-a90ef680-bd0f-11e9-8321-7bdd6e6e6404.png">

**Comment by allisonheath** [comment]
I'll just note for the rest of the world it's dd/mm/yy - I happen to like the form `12 Aug 2019` for clarity.
