### ISSUE TITLE
Browser back button does the wrong thing re: the document list

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#469]
I go to https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_BHJXBDQK/documents
I click `>` or `2` at the bottom to go to the second page.
I press the back button to go back to page 1.
I get taken to https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_BHJXBDQK/basic-info or https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_BHJXBDQK/documents/new-document or randomly somewhere else instead of back to page 1.

I go to https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_BHJXBDQK/documents
Like before, I click over to page 2 to find a document that isn't on the first page.
I click on the document.
I press the back button to go back to page 2.
I get taken to page 1 of the documents list instead of page 2.

**Comment by bdolly** [comment]
I've also noticed this and think it's due to the pagination and modals not pushing onto the browser history

**Comment by XuTheBunny** [comment]
The pagination only changes the files within current tab, and if you click on the back button from the browser it will take you to the previous page you visit, since "page1" and "page 2" on files were not considered as a new page.
