### ISSUE TITLE
UI elements are broken without downloadable fonts

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#471]
macOS 10.14.6
Firefox 69.0.1 (64-bit)

![Screen Shot 2019-09-18 at 4 18 06 PM](https://user-images.githubusercontent.com/201996/65183040-96838d80-da30-11e9-9a86-e4a7f2270aec.png)

vs
![Screen Shot 2019-09-18 at 4 17 49 PM](https://user-images.githubusercontent.com/201996/65183046-984d5100-da30-11e9-8338-f7bb3196228c.png)

Please just use regular svgs for icons. Blocking webfont downloads shouldn't catastrophically break the interface.

**Comment by dankolbman** [comment]
Are you blocking certain domains from requests? We can look into how easy it is to turn the font  into svgs, but it's probably not going to be straight forward and we probably won't be able to address this.

**Comment by fiendish** [comment]
Not blocking domains, blocking all webfont downloads

**Comment by dankolbman** [comment]
I agree that icon fonts have downsides, but I don't believe that the effort needed to 'un-break' them is going to payoff here. It's likely easier for the user to not block them.
