### ISSUE TITLE
shrink edit document type selectors

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#488]
If the document type selectors were slightly smaller in the document edit modal, I wouldn't have to scroll to get to the description field.

<img width="765" alt="Screen Shot 2019-09-23 at 10 33 34 PM" src="https://user-images.githubusercontent.com/201996/65477081-22435280-de53-11e9-9faa-a20b76756d67.png">

**Comment by fiendish** [comment]
541 does not address this

**Comment by bdolly** [comment]
marking this as `wontfix` until we get empirical evidence that supports this being an issue for a cohort vs single user

**Comment by allisonheath** [comment]
Isn't it pretty well known that scrolling isn't great in a modal if it can fit on the screen?

If it was a cross-browser issue, that's one thing, but it looks like this should easily fit?
