### ISSUE TITLE
Study list view default 

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-data-tracker#505]
user feedback from`ADMIN` role users suggest that by defaulting the study view to list/table view will allow them to more efficiently skim the study list

**Comment by allisonheath** [comment]
I still think this is for all users - not just `ADMIN`

**Comment by allisonheath** [comment]
Actually - does it remember what you clicked on last, maybe that's all it really needs.

**Comment by bdolly** [comment]
not yet
