### ISSUE TITLE
Factor out documents application

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#508]
Now that the data tracker is becoming more complex with an increasing amount of responsibilities, it may be helpful to start factoring out contained logic into sub-applications. The document flow is a good place to start as it already has a couple flows that are unique to the documents tab.

The structure of the sub-application will be similar to how our application is ordered already, just within its own subdirectory. This will allow the sub-app to consume any higher level components.
This is an example of how that layout may look:
```
src/documents
├── components
│   ├── DocumentList.js
│   └── FileUpload.js
├── forms
│   ├── NewDocumentForm.js
│   └── UpdateDocumentForm.js
├── index.js
├── mutations.js
├── queries.js
├── routes.js
├── fragments.js
└── views
    ├── Document.js
    ├── DocumentList.js
    └── NewDocument.js
```

**Comment by bdolly** [comment]
@dankolbman I think mutations, queries, fragments could live in a`state` dir. Would utility files continue to live at the `/src/common` or should specific ones be within the sub-app?

**Comment by dankolbman** [comment]
@bdolly I think we can keep our current layout for the global stuff and transisition them into specific apps as needed, so teh global components will stay in `src/components`
