### ISSUE TITLE
Cannot upload a new document when there is no documents exist from Safari

### ISSUE THREAD

**Issue by XuTheBunny** [kids-first/kf-ui-data-tracker#520]
## UI Version

semantic-ui-react - 0.87.1

## URL

It can be any study that doesn't have documents.
http://localhost:3000/study/SD_745WVV0R/documents

## ScreenShot(s)
**Only happens on Safari**
<img width="1440" alt="Screen Shot 2019-10-17 at 12 14 54 PM" src="https://user-images.githubusercontent.com/32206137/67027596-cf6a5d00-f0d7-11e9-9a45-c35a9d4e51fc.png">
<img width="1440" alt="Screen Shot 2019-10-17 at 12 15 16 PM" src="https://user-images.githubusercontent.com/32206137/67027594-cf6a5d00-f0d7-11e9-9cc5-eedf77aeecb8.png">

## Steps To Reproduce

Go to any study that doesn't have any documents and try to add a new document

## Expected Behavior

When clicking on the upload button, expect the button change to "UPLOADING..." stage

## Observed Behavior

Nothing changed on the page, the update button is active but not change to "UPLOADING..." stage
There is no GraphQL sent out on clicking the upload button

**Comment by bdolly** [comment]
@XuTheBunny what version of safari is this bug tested in?
