### ISSUE TITLE
Create new study status screen

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#546]
## Persona (link)

Admins

## Requirements

We should replace the 'Creating Study' screen with a status report that gets update as the various tasks are completed.

The check list of the tasks that are displayed on this screen should be as follows:

1. Registered study with Data Service: <kf_id>
2. Created storage bucket: <s3 url>
3. Created Cavatica analysis projects: <list of external links to new analysis projects>
4. Created Cavatica delivery project: <external link to delivery project.

The above may be determined by the presence of the following event types for the new study:

- `SD_CRE` -> study has been registered in Data Service
- Bucket creation:
  - `BK_STR` Bucket creation started
  - `BK_SUC` Bucket creation finished
  - `BK_ERR` Bucket creation had an error, error is in message
- Project Creation
 - `PR_STR` New Cavatica projects have started to be allocated
 - `PR_SUC` New Cavatica projects were created
 - `PR_ERR` Error creating new Cavatica projects

Once each step has completed successfully, buttons to take the user to common tasks like study info, and documents view, should be displayed.
There should also be a de-emphasized button that will take the user to the study info page despite the study not being fully set up yet.

## Motivation/Goal

To better communicate the next actions required from the administrator after creating a new study.

## Supporting Evidence (qual or quant)

A user is currently dropped into a study's documents tab immediately after starting the creation process which is both erroneous and unhelpful.

**Comment by bdolly** [comment]
@dankolbman please specifically reference personas from https://docs.google.com/document/d/19rFy1SaK22Pamdwk5vjYe7pgEw3vLHruHeG3zXHbQnc/edit?usp=sharing with evidence of how this feature supports the goals for the specified user group. This helps focus features around use cases and not just general All Users
