### ISSUE TITLE
Need a 404 page indicating invalid URL

### ISSUE THREAD

**Issue by XuTheBunny** [kids-first/kf-ui-data-tracker#549]
## Persona (link)

All users

## Requirements

Need to valid url input, capturing invalid study ID or document ID, and redirector user to a 404 page.

## Motivation/Goal

Need to have a fall-back page instead of showing console errors to all users.

- Capture invalid study id -> redirect user to "Study not found" page
- Capture invalid document id -> redirect user to "Document not found" page
- Capture all other cases with a general 404 page

## Supporting Evidence (qual or quant)

We are trying to avoid user to see any page like this when put the invalid urls.
![image](https://user-images.githubusercontent.com/32206137/69576753-fb141900-0f9a-11ea-82c2-477439c5ad8c.png)

**Comment by bdolly** [comment]
@XuTheBunny  please specifically reference personas from https://docs.google.com/document/d/19rFy1SaK22Pamdwk5vjYe7pgEw3vLHruHeG3zXHbQnc/edit?usp=sharing with evidence of how this feature supports the goals for the specified user group. This helps focus features around use cases and not just general All Users
