### ISSUE TITLE
Add page titles to all views

### ISSUE THREAD

**Issue by XuTheBunny** [kids-first/kf-ui-data-tracker#550]
## Persona (link)

All users would benefit from this feature.

## Requirements

Have one unique and descriptive page title for each view we have, including the admin routes and regular routes.

## Motivation/Goal

Provide descriptive page title when user navigates through the app. It's convenient for them to get to certain page when checking their browser visit history. 

## Supporting Evidence (qual or quant)

Current page title a lacking information.
![image](https://user-images.githubusercontent.com/32206137/69580310-53024e00-0fa2-11ea-8dc8-9ca6b1b4420f.png)

**Comment by bdolly** [comment]
@XuTheBunny please specifically reference personas from https://docs.google.com/document/d/19rFy1SaK22Pamdwk5vjYe7pgEw3vLHruHeG3zXHbQnc/edit?usp=sharing with evidence of how this feature supports the goals for the specified user group. This helps focus features around use cases and not just general All Users
