### ISSUE TITLE
Add icon mappings for new event types

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#551]
## Persona (link)

Admins, Developers

## Requirements

Add icon mappings for the new event types to the [event enums](https://github.com/kids-first/kf-ui-data-tracker/blob/af89722e7dd26bdd689d85f068cf0cdc8d0a8702/src/common/enums.js#L79):
- `PR_STR`
- `PR_ERR`
- `PR_SUC`
- `BK_STR`
- `BK_ERR`
- `BK_SUC`

## Motivation/Goal

Having mappings for these events will allow us to more easily process the event log by being able to scan for errors, successes, or notifications more easily as opposed to many unknown fields as is currently displayed:

![Screen Shot 2019-11-26 at 9 41 07 AM](https://user-images.githubusercontent.com/2495894/69643738-b9827d00-1031-11ea-8692-771930df13a0.png)

## Supporting Evidence (qual or quant)

Many unknown event types results in a log that may have known errors or successes marked unhelpfully as `❓`. This makes it easy to miss events that should have attention drawn to them.

**Comment by bdolly** [comment]
@dankolbman please specifically reference personas from https://docs.google.com/document/d/19rFy1SaK22Pamdwk5vjYe7pgEw3vLHruHeG3zXHbQnc/edit?usp=sharing with evidence of how this feature supports the goals for the specified user group. This helps focus features around use cases and not just general All Users
