### ISSUE TITLE
Add latest published version to study rows

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#552]
## Persona (link)

Admins, developers, wranglers, investigators

## Requirements

Add the latest published release version to the study table and cards in the study list view.
For studies that have not been released, it should read as `Not Published`.

Hovering over the version tag should display the time ago of the release to give a sense of whether this release was recent or not.

We may retrieve a study's latest publication with the `allReleases` query on the coordinator using `state=published` filter, or with the `allStudies` query and a `releases(state: "published", first: 1)` sub query.

## Motivation/Goal

Being aware of a study's published version from the study list view will allow admins and wranglers to quickly parse out studies that have been released or not and quickly let the investigator of the study know if their study has been published recently or at all.

## Supporting Evidence (qual or quant)

It is currently very difficult for users to pick out studies that have been published to the portal. This task requires manual cross-comparison between the data tracker and the portal, often requiring navigation in and out of studies to get the short name to compare to facets on the portal.
Furthermore, it is impossible to tell what version has been published to the portal, when it last occurred, and what changes were made.

**Comment by bdolly** [comment]
@dankolbman please specifically reference personas from https://docs.google.com/document/d/19rFy1SaK22Pamdwk5vjYe7pgEw3vLHruHeG3zXHbQnc/edit?usp=sharing with evidence of how this feature supports the goals for the specified user group. This helps focus features around use cases and not just general _All Users_
