### ISSUE TITLE
drag/drop upload box - not clear that you can update docs with drag and drop

### ISSUE THREAD

**Issue by chris-s-friedman** [kids-first/kf-ui-data-tracker#564]
It's not clear that you can update documents by dragging and dropping. The box currently says `to upload Study Documents drag and drop a file here`. Maybe it could say `to upload or update Study Documents...`?

**Comment by dankolbman** [comment]
We can update the wording like so:

### Current
<img width="540" alt="Screen Shot 2020-02-12 at 9 48 23 AM" src="https://user-images.githubusercontent.com/2495894/74346079-077b6700-4d7d-11ea-996f-c09ebfd8ab1b.png">

### Updated
<img width="618" alt="Screen Shot 2020-02-12 at 9 49 39 AM" src="https://user-images.githubusercontent.com/2495894/74346096-0ea27500-4d7d-11ea-8a44-3deee1ba25e2.png">

**Comment by dankolbman** [comment]
Also addresses #392

**Comment by chris-s-friedman** [comment]
Looks good to me
