### ISSUE TITLE
Add new file type: dbGaP file

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-ui-data-tracker#602]
We need a new file type in the data tracker - dbGaP file. 

We are responsible for submitting manifests & study configs to dbgap when preparing to release a study. These files should be versioned controlled and are a trackable product of the a study. Right now they are being put in as "Other".

**Comment by dankolbman** [comment]
*title:* dbGaP Submission File
*description:* A document formatted to the dbGaP submission specification for uploading to dbGaP during a new release.
