### ISSUE TITLE
Strip FV_# prefix from filename if it matches an existing file version

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#792]
**Sender**: patcherton.fixesthings@gmail.com
**Comment**: If you download a file version, you get one with the version ID prefixed on the filename. Re-uploading it could intelligently de-prefix the file name if the prefix matches any existing file version IDs for that file.
[Open #23 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/23)

<a href='https://usersnappublic.s3.amazonaws.com/2020-07-20/16-16/3ebbfb75-d895-4b7f-8fd3-5f4d6db6d00a.png'>![⚠️ - Strip FV_# prefix from filename if it matches an existing file version](https://usersnappublic.s3.amazonaws.com/2020-07-20/16-16/c943981d-284d-42a0-ac97-ad8ad8609506.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-07-20/16-16/3ebbfb75-d895-4b7f-8fd3-5f4d6db6d00a.png'>Download original image</a>

**Browser**: Safari 13 (macOS Mojave)
**Referer**: [https://deploy-preview-791--kf-ui-data-tracker.netlify.app/study/SD_ME0WME0W/documents/SF_C9HH2FPS](https://deploy-preview-791--kf-ui-data-tracker.netlify.app/study/SD_ME0WME0W/documents/SF_C9HH2FPS)
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1089

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by XuTheBunny** [comment]
Obsolete
