### ISSUE TITLE
Upload document button does not route

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#835]
[Open #46 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/46)
**Notes**:
 - (1) Does not complete and route to next page

<a href='https://usersnappublic.s3.amazonaws.com/2020-08-13/16-34/bc920f0d-f93a-4234-b02f-1d71e64d503f.png'>![⚠️ - Upload document button does not route](https://usersnappublic.s3.amazonaws.com/2020-08-13/16-34/0d81d52d-337d-4f6d-8e18-7a5f783ef102.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2020-08-13/16-34/bc920f0d-f93a-4234-b02f-1d71e64d503f.png'>Download original image</a>

**Browser**: Firefox 79 (macOS Mojave)
**Referer**: [https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents/new-document](https://kf-ui-data-tracker.kidsfirstdrc.org/study/SD_ME0WME0W/documents/new-document)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 838

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jharenza** [comment]
Second this! I just had the issue where it would say "UPLOAD..."
