### ISSUE TITLE
uploaded files deletable by anyone

### ISSUE THREAD

**Issue by jharenza** [kids-first/kf-ui-data-tracker#837]
## Steps To Reproduce
When I was deleting my several mistaken uploads due to #835, I noticed that I am able to select anyone's documents and delete. Less of a bug and more of a dangerous feature.

## Expected Behavior
I think you should only be able to delete your own files.

**Comment by dankolbman** [comment]
Thanks @jharenza ! The ability to delete files is reserved for administrators, other users will not have the option to delete any documents.

**Comment by jharenza** [comment]
Does that mean I am mistakenly an admin? I deleted my duplicated files today.

**Comment by dankolbman** [comment]
I updated your account to be an 'investigator' so you won't be able to delete files anymore.
