### ISSUE TITLE
http 400 error from https://kf-release-coord.kidsfirstdrc.org/graphql

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#950]
## Relevant View or Screen

https://data-tracker.kidsfirstdrc.org/study/SD_JWS3V24D/basic-info/info

## Steps To Reproduce

1. Visit study page in data tracker UI
1. Look in console

<img width="1099" alt="Screen Shot 2020-12-22 at 11 47 34 AM" src="https://user-images.githubusercontent.com/201996/102922604-85070d80-444b-11eb-8088-89a2aa094d61.png">

Browser: Safari 14.0.1 
OS: macOS 10.14.6 Mojave

**Comment by dankolbman** [comment]
This should be resolved in the next release as we've deprecated all dependency on the Release Coordinator's api.
