### ISSUE TITLE
Duplicate variable darkModeMediaQuery syntax errors in console

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#951]
## Relevant View or Screen

https://data-tracker.kidsfirstdrc.org

## Steps To Reproduce

1. Visit data tracker UI.
2. Look in console.

<img width="1048" alt="Screen Shot 2020-12-22 at 11 51 21 AM" src="https://user-images.githubusercontent.com/201996/102922994-2a21e600-444c-11eb-878f-97a2636d778d.png">

Browser: Safari 14.0.1
OS: macOS 10.14.6 Mojave

**Comment by XuTheBunny** [comment]
Obsolete
