### ISSUE TITLE
"Upload Document"/"Choose a File" buttons don't do anything

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#952]
Browser: Safari 14.0.1
OS: macOS 10.14.6 Mojave

## Relevant View or Screen

https://data-tracker.kidsfirstdrc.org/study/SD_JWS3V24D/documents

![Screen Shot 2020-12-22 at 1 36 33 PM](https://user-images.githubusercontent.com/201996/102931115-ff8b5980-445a-11eb-8a44-df513a366e5f.png)

and

https://data-tracker.kidsfirstdrc.org/study/SD_JWS3V24D/documents/SF_TH5PZ6BD  ( click "New Version" )

![Screen Shot 2020-12-22 at 12 08 14 PM](https://user-images.githubusercontent.com/201996/102931119-00bc8680-445b-11eb-806d-30d13981b804.png)

## Steps To Reproduce

1. Click any of the indicated buttons in the attached screenshots.
1. Nothing happens

## Expected Behavior

File selection view should open.

**Comment by XuTheBunny** [comment]
I found this Apple community bug report tacking:
https://discussions.apple.com/thread/252051818

**Comment by XuTheBunny** [comment]
Close due to Apple released Safari 15 macOS Big Sur and macOS Catalina devices on September 20, 2021, this issue is fixed.
