### ISSUE TITLE
API repo link at bottom of page is broken

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-data-tracker#953]
## Relevant View or Screen

https://data-tracker.kidsfirstdrc.org

## Steps To Reproduce

Click on "v3.6" at bottom of page next to "Study Creator API"

<img width="478" alt="Screen Shot 2020-12-23 at 11 37 28 PM" src="https://user-images.githubusercontent.com/201996/103067356-ef1cd100-4577-11eb-8711-78928656e914.png">

The linked page does not exist and you get a 404 on github.

## Expected Behavior

It should be working link instead of a 404.

**Comment by dankolbman** [comment]
This is being tracked here: https://github.com/kids-first/kf-devops/issues/508
