### ISSUE TITLE
Sharable paths

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#990]
## Feature Justification

It would be helpful if we could share links directly to folders within a study's documents. This will allow users to send urls directly to others that will land them within the correct folder rather than having to find it within the study.

## Proposed Change or Addition

We can use hash routing by updating the url hash whenever the user navigates into a directory. When a user lands back on a page with this hash route, we can send them directly to the requested folder.

![Screen Shot 2021-02-26 at 11 26 14 AM](https://user-images.githubusercontent.com/2495894/109327232-1ae15f00-7826-11eb-8103-d8bfe9b93c12.png)

**Comment by XuTheBunny** [comment]
GitHub system error, this issue has been solved and the pull request is merged into master.
