### ISSUE TITLE
Use breadcrumbs for paths

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#992]
**Comment**: See the breadcrumb component in Semantic: https://react.semantic-ui.com/collections/breadcrumb/#types-shorthand
[Open #98 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/98)

<a href='https://usersnappublic.s3.amazonaws.com/2021-02-26/17-32/605f8a64-cd04-4566-87be-253ffc39550c.png'>![⚠️ - Use breadcrumbs for paths](https://usersnappublic.s3.amazonaws.com/2021-02-26/17-32/e7589c28-8b10-4d32-b14e-c8bc0e94af1e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-02-26/17-32/605f8a64-cd04-4566-87be-253ffc39550c.png'>Download original image</a>

**Browser**: Firefox 85 (macOS Mojave)
**Referer**: [http://localhost:3000/study/SD_ME0WME0W/documents](http://localhost:3000/study/SD_ME0WME0W/documents)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 838

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by XuTheBunny** [comment]
GitHub system error, this issue has been solved and the pull request is merged into master.
