### ISSUE TITLE
Open folder from tree on click

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#993]
**Comment**: Instead of having an additional button, it would be nice to be able to click on the folder itself to open it in the browser.
[Open #99 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/99)
**Notes**:
 - (1) Clicking on folder should automatically open it.

<a href='https://usersnappublic.s3.amazonaws.com/2021-02-26/17-34/c8164815-b6be-40a1-a094-1f0f751fa97d.png'>![⚠️ - Open folder from tree on click](https://usersnappublic.s3.amazonaws.com/2021-02-26/17-34/4b476cee-5de9-489a-aac9-5cf276e441c2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-02-26/17-34/c8164815-b6be-40a1-a094-1f0f751fa97d.png'>Download original image</a>

**Browser**: Firefox 85 (macOS Mojave)
**Referer**: [http://localhost:3000/study/SD_ME0WME0W/documents](http://localhost:3000/study/SD_ME0WME0W/documents)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 838

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by XuTheBunny** [comment]
Plan to not make updates for this.
