### ISSUE TITLE
Search documents by tags

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#994]
[Open #100 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/100)
**Notes**:
 - (1) Search and filter by these tags
 - (2) Perhaps the search bar can be more powerful and prominent to allow us to search by names or tags.
 - (3) We'll have to figure out how to display paths when we are in 'search mode'

<a href='https://usersnappublic.s3.amazonaws.com/2021-02-26/17-37/594a90c5-f1b9-4a10-8ead-798bffb280db.png'>![⚠️ - Search documents by tags](https://usersnappublic.s3.amazonaws.com/2021-02-26/17-37/e6f130cb-207e-47f2-827d-06f76fb0d42b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-02-26/17-37/594a90c5-f1b9-4a10-8ead-798bffb280db.png'>Download original image</a>

**Browser**: Firefox 85 (macOS Mojave)
**Referer**: [http://localhost:3000/study/SD_ME0WME0W/documents](http://localhost:3000/study/SD_ME0WME0W/documents)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 838

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by XuTheBunny** [comment]
GitHub system error, this issue has been solved and the pull request is merged into master.
