### ISSUE TITLE
Copy download link button returns wrong thing from folder view

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#999]
**Sender**: chrisfriedman@d3b.center
[Open #104 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-oy1k/p/data-tracker-cae9537d/104)

<a href='https://usersnappublic.s3.amazonaws.com/2021-03-04/22-48/a9eddf64-a87e-459d-934e-e6d12bac7f99.png'>![⚠️ - copy download link button returns wrong thing from folder view](https://usersnappublic.s3.amazonaws.com/2021-03-04/22-48/2e4f9268-6cfe-4ba2-a131-569aa1d10f6f.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-03-04/22-48/a9eddf64-a87e-459d-934e-e6d12bac7f99.png'>Download original image</a>

**Browser**: Firefox 86 (Macintosh)
**Referer**: [https://data-tracker.kidsfirstdrc.org/study/SD_Z6MWD3H0/documents](https://data-tracker.kidsfirstdrc.org/study/SD_Z6MWD3H0/documents)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 826

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by XuTheBunny** [comment]
GitHub system error, this issue has been solved and the pull request is merged into master.
